[package]
name = "connx"
version = "0.1.0"
edition = "2021"
authors = ["MDGSF <mdgsf@qq.com>"]
license = "MIT"
description = "toolkit for coding"
homepage = ""
documentation = "https://docs.rs/connx"
repository = "https://github.com/MDGSF/connx"
readme = "README.md"

[dependencies]
